# Generated by Django 6.0.1 on 2026-01-20 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_role_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='(Obligatorio)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.role', verbose_name='Rol de usuario'),
        ),
    ]
