# Generated by Django 6.0.1 on 2026-01-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(max_length=9, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Informacion Personal',
                'verbose_name_plural': 'Informaciones Personales',
                'db_table': 'info_personal',
                'ordering': ['fecha_nacimiento'],
            },
        ),
    ]
