# Generated by Django 6.0.1 on 2026-01-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_infopersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
            },
        ),
        migrations.AlterModelOptions(
            name='infopersonal',
            options={'ordering': ('-country',), 'verbose_name': 'Informacion Personal', 'verbose_name_plural': 'Datos Personales'},
        ),
        migrations.RemoveField(
            model_name='infopersonal',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='infopersonal',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='infopersonal',
            name='telefono',
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='address',
            field=models.TextField(blank=True, help_text='Obligatorio', null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='age',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99), (100, 100)], default=18, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='birthday',
            field=models.DateField(blank=True, help_text='Obligatorio', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='country',
            field=models.CharField(choices=[('ES', 'ESPAÑA'), ('FR', 'FRANCIA'), ('DE', 'ALEMANIA'), ('IT', 'ITALIA')], default='ES', help_text='Obligatorio', max_length=3, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='document',
            field=models.CharField(blank=True, help_text='Obligatorio', max_length=15, null=True, unique=True, verbose_name='Documento(DNI, NIE, Pasaporte)'),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='phone',
            field=models.CharField(blank=True, help_text='Opcional', max_length=11, null=True, unique=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_personal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Obligatorio', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.ciudadmodel', verbose_name='Ciudad'),
        ),
    ]
